version: '3'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=precess-vertex-spice-charge
  backend:
   # use the image we defined in the earlier exercises
    build: /Users/laurapesola/Private Stuff/docker-devops-kurssi/backend-example-docker 
    container_name: hy-back
    ports:
       - 8000:8000
    environment: 
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=precess-vertex-spice-charge
      - DB_HOST=postgres
  frontend:
   # use the image we defined in the earlier exercises
    build: /Users/laurapesola/Private Stuff/docker-devops-kurssi/frontend-example-docker 
    volumes: 
       - /Users/laurapesola/Private Stuff/docker-devops-kurssi/docker-mount/logs.txt:/app/logs.txt
    container_name: hy-front 
    ports:
      - 5000:5000

