version: '3'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=precess-vertex-spice-charge
  backend:
    build: /Users/laurapesola/Private Stuff/docker-devops-kurssi/backend-example-docker 
    container_name: hy-back
    depends_on:
     - postgres
     - redis
    ports:
       - 8000:8000
    environment: 
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=precess-vertex-spice-charge
      - DB_HOST=postgres
  frontend:
    build: /Users/laurapesola/Private Stuff/docker-devops-kurssi/frontend-example-docker 
    depends_on: 
     - backend 
    volumes: 
       - /Users/laurapesola/Private\ Stuff/docker-devops-kurssi/docker-mount/logs.txt:/app/logs.txt
    container_name: hy-front 
    ports:
      - 5000:5000
  nginx:
    image: nginx
    container_name: nginx
    depends_on: 
     - frontend
     - backend
    volumes: 
     - /Users/laurapesola/Private Stuff/docker-devops-kurssi/docker-devops/wk2/ex2-4/nginx.conf:/etc/nginx/nginx.conf
    ports:
    - 80:80
      

